from time import sleep
import zipfile

sleep(1)
print("LOG:Procesando cancion numero 1 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 2 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 3 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 4 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 5 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 6 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 7 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 8 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 9 de 10",flush=True)
sleep(1)
print("LOG:Procesando cancion numero 10 de 10",flush=True)
print("Buenas....",flush=True)
sleep(1)
print(f"LOG:Normalizando las 10 canciones",flush=True)
print("Normalizando canciones",flush=True)    
sleep(5)
with open("./algo.txt", "w") as fo:
    fo.write("Saludos\n")
zip = zipfile.ZipFile("./songs_list/"+"SL_12152632544"+".zip", "w", zipfile.ZIP_STORED,compresslevel=1)

zip.write("./algo.txt")
zip.close()
